import "./globals.css";
import Sidebar from "@/components/Sidebar";
import MainHeader from "@components/MainHeader";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="flex w-full">
            <Sidebar />
            <main className="app flex-grow bg-[#EAEDF2]">
                <MainHeader />
                {children}
            </main>
        </div>
      </body>
    </html>
  );
}
